Simple build fixes.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,6 +14,14 @@ jobs:
             matrix:
                 python-version:
                     - 3.8
+        services:
+            mysql:
+                image: mariadb:10.5
+                env:
+                    MYSQL_ROOT_PASSWORD: root
+                ports:
+                - 3306:3306
+                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
         steps:
             -
                 name: Checkout
@@ -27,8 +35,17 @@ jobs:
                 name: Install build dependencies
                 run: |
                     python -m pip install --upgrade pip
-                    pip install poetry tox
+                    pip install poetry tox pre-commit
             -
                 name: Test with tox
                 run: |
                     tox -v
+            -
+                name: Build the Docker image
+                run: |
+                    docker build .
+            -
+                name: Run coveralls
+                # the || true is because coveralls returns a nonzero exit code on warnings, etc.
+                run: |
+                    coveralls || true
